<?php

/**
 * @file
 * Fraction module code.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fraction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fraction module.
    case 'help.page.fraction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a field for storing decimals as fractions, for maximum precision.') . '</p>';
      return $output;

    default:
  }
}
