<?php

/**
 * @file
 * Fraction
 */

/***************************************************************
 * Drupal hooks
 * **************************************************************/

/**
 * Implements of hook_field_info().
 */
function fraction_field_info() {
  return array(
    'fraction' => array(
      'label' => t('Fraction'),
      'description' => t('This field stores a decimal in fraction form (with a numerator and denominator) for maximum precision.'),
      'settings' => array(),
      'instance_settings' => array(),
      'default_widget' => 'fraction_textfields',
      'default_formatter' => 'fraction_fixed',
    ),
  );
}

/**
 * Implements of hook_field_info().
 */
function fraction_field_widget_info() {
  return array(
    'fraction_textfields' => array(
      'label' => t('Text fields'),
      'field types' => array('fraction'),
      'settings' => array(),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements of hook_field_info().
 */
function fraction_field_formatter_info() {
  return array(
    'fraction_fixed' => array(
      'label' => t('Fixed precision'),
      'field types' => array('fraction'),
      'settings' => array('precision' => 2),
    ),
  );
}
